PRINT Db_Name()+', Criação da Procedure USPPontoRetiradaListar'

GO
--------------------------------------------------------------------------------------
-- OBJETO: USPPontoRetiradaListar – RESPONSÁVEL: Anderson – DATA: 10/10/2018 – 
--------------------------------------------------------------------------------------
IF EXISTS( SELECT
               NAME
           FROM
               SYSOBJECTS
           WHERE
             XTYPE = 'P'
             AND NAME = 'USPPontoRetiradaListar' )
    DROP PROCEDURE USPPontoRetiradaListar

GO

CREATE PROCEDURE USPPontoRetiradaListar
		   
AS
    SET NOCOUNT ON

SELECT
	TB_PONTORETIRADA.IDPONTORETIRADA, 
	TB_PONTORETIRADA.NOMEFANTASIA, 
	TB_PONTORETIRADA.RAZAOSOCIAL, 
	TB_PONTORETIRADA.CNPJ, 
	TB_PONTORETIRADA.IE, 
	TB_PONTORETIRADA.ENDERECO, 
	TB_PONTORETIRADA.NUMERO, 
	TB_PONTORETIRADA.COMPLEMENTO, 
	TB_PONTORETIRADA.CIDADE, 
	TB_PONTORETIRADA.CEP, 
	TB_PONTORETIRADA.BAIRRO, 
	TB_PONTORETIRADA.ESTADO, 
	TB_PONTORETIRADA.EMAIL, 
	TB_PONTORETIRADA.IDSTATUS, 
	TB_STATUS.[STATUS], 
	TB_PONTORETIRADA.DATACADASTRO, 
	TB_PONTORETIRADA.LATITUDE, 
	TB_PONTORETIRADA.LONGITUDE, 
	TB_PONTORETIRADA.CODINTERNO

FROM TB_STATUS 
	INNER JOIN
TB_PONTORETIRADA ON TB_STATUS.IDSTATUS = TB_PONTORETIRADA.IDSTATUS