PRINT Db_Name()+', Criação da Procedure USPPranchaListar'

GO
--------------------------------------------------------------------------------------
-- OBJETO: USPPranchaListar – RESPONSÁVEL: Anderson – DATA: 10/10/2018 – 
--------------------------------------------------------------------------------------
IF EXISTS( SELECT
               NAME
           FROM
               SYSOBJECTS
           WHERE
             XTYPE = 'P'
             AND NAME = 'USPPranchaListar' )
    DROP PROCEDURE USPPranchaListar

GO

CREATE PROCEDURE USPPranchaListar
		   
AS
    SET NOCOUNT ON

SELECT
	TB_PRANCHA.IDPRANCHA, 
	TB_PRANCHA.PRANCHA, 
	TB_PRANCHA.DESCRICAO, 
	TB_PRANCHA.VOLUME, 
	TB_PRANCHA.POLEGADAS, 
	TB_PRANCHA.ESPESSURA, 
	TB_PRANCHA.IDFORNECEDOR, 
	TB_FORNECEDOR.NOMEFANTASIA, 
	TB_FORNECEDOR.RAZAOSOCIAL, 
	TB_FORNECEDOR.CNPJ, 
	TB_FORNECEDOR.CODINTERNO AS CODINTERNOFORNECEDOR, 
	TB_PRANCHA.DATACADASTRO, 
	TB_PRANCHA.IDSTATUS, 
	TB_STATUS.STATUS, 
	TB_PRANCHA.CODINTERNO AS CODINTERNOPRANCHA
FROM
	TB_PRANCHA 
INNER JOIN
	TB_FORNECEDOR ON TB_PRANCHA.IDFORNECEDOR = TB_FORNECEDOR.IDFORNECEDOR 
INNER JOIN
	TB_STATUS ON TB_PRANCHA.IDSTATUS = TB_STATUS.IDSTATUS