PRINT Db_Name()+', Criação da Procedure USPReservasListar'

GO
--------------------------------------------------------------------------------------
-- OBJETO: USPReservasListar – RESPONSÁVEL: Anderson – DATA: 10/10/2018 – 
--------------------------------------------------------------------------------------
IF EXISTS( SELECT
               NAME
           FROM
               SYSOBJECTS
           WHERE
             XTYPE = 'P'
             AND NAME = 'USPReservasListar' )
    DROP PROCEDURE USPReservasListar

GO

CREATE PROCEDURE USPReservasListar
		   
AS
    SET NOCOUNT ON

SELECT
	TB_RESERVAS.IDRESERVA, 
	TB_RESERVAS.IDPRANCHA, 
	TB_PRANCHA.PRANCHA, 
	TB_PRANCHA.DESCRICAO, 
	TB_PRANCHA.VOLUME, 
	TB_PRANCHA.POLEGADAS, 
	TB_PRANCHA.ESPESSURA, 
	TB_PRANCHA.IDFORNECEDOR, 
	TB_FORNECEDOR.NOMEFANTASIA, 
	TB_FORNECEDOR.RAZAOSOCIAL, 
	TB_RESERVAS.IDCLIENTE, 
	TB_CLIENTE.NOME, 
	TB_CLIENTE.SOBRENOME, 
	TB_CLIENTE.IDFACEBOOK, 
	TB_CLIENTE.EMAIL, 
	TB_RESERVAS.IDPLANO, 
	TB_PLANOS.PLANO, 
	TB_PLANOS.VALOR, 
	TB_PLANOS.DIAS, 
	TB_PLANOS.MENSAL, 
	TB_RESERVAS.DATARETIRADA, 
	TB_RESERVAS.DATAENTREGA, 
	TB_RESERVAS.DATACADASTRO, 
	TB_RESERVAS.IDSTATUS, 
	TB_STATUS.[STATUS], 
	TB_RESERVAS.CODINTERNO

FROM
TB_RESERVAS 
	INNER JOIN
TB_PRANCHA ON TB_RESERVAS.IDPRANCHA = TB_PRANCHA.IDPRANCHA 
	INNER JOIN
TB_CLIENTE ON TB_RESERVAS.IDCLIENTE = TB_CLIENTE.IDCLIENTE 
	INNER JOIN
TB_PLANOS ON TB_RESERVAS.IDPLANO = TB_PLANOS.IDPLANO 
	INNER JOIN
TB_STATUS ON TB_RESERVAS.IDSTATUS = TB_STATUS.IDSTATUS 
	INNER JOIN
TB_FORNECEDOR ON TB_PRANCHA.IDFORNECEDOR = TB_FORNECEDOR.IDFORNECEDOR