PRINT Db_Name()+', Criação da Procedure USPFornecedorBuscar'

GO
--------------------------------------------------------------------------------------
-- OBJETO: USPFornecedorBuscar – RESPONSÁVEL: Anderson – DATA: 03/11/2018 – 
--------------------------------------------------------------------------------------
IF EXISTS( SELECT
               NAME
           FROM
               SYSOBJECTS
           WHERE
             XTYPE = 'P'
             AND NAME = 'USPFornecedorBuscar' )
    DROP PROCEDURE USPFornecedorBuscar

GO

CREATE PROCEDURE USPFornecedorBuscar
		
	@CNPJ varchar(20),
	@RAZAOSOCIALNOMEFANTASIA varchar(40),
	@CODINTERNO varchar(40) 
		   
AS
    SET NOCOUNT ON

SELECT     
	TB_FORNECEDOR.IDFORNECEDOR, 
	TB_FORNECEDOR.NOMEFANTASIA, 
	TB_FORNECEDOR.RAZAOSOCIAL, 
	TB_FORNECEDOR.CNPJ, 
	TB_FORNECEDOR.ENDERECO, 
	TB_FORNECEDOR.NUMERO, 
	TB_FORNECEDOR.COMPLEMENTO, 
	TB_FORNECEDOR.BAIRRO, 
	TB_FORNECEDOR.CEP, 
	TB_FORNECEDOR.CIDADE, 
	TB_FORNECEDOR.ESTADO, 
	TB_FORNECEDOR.DATACADASTRO, 
	TB_FORNECEDOR.IDSTATUS, 
	TB_STATUS.[STATUS], 
	TB_FORNECEDOR.IE, 
	TB_FORNECEDOR.EMAIL, 
	TB_FORNECEDOR.LATITUDE, 
	TB_FORNECEDOR.LONGITUDE, 
	TB_FORNECEDOR.CODINTERNO,
	TB_FORNECEDOR.TELEFONE1,
	TB_FORNECEDOR.TELEFONE2,
	TB_FORNECEDOR.TELEFONE3,
	TB_FORNECEDOR.TELEFONE4,
	TB_FORNECEDOR.PONTOENTREGARETIRADA,
	TB_FORNECEDOR.FABRICANTE
FROM TB_FORNECEDOR 
	INNER JOIN
TB_STATUS ON TB_FORNECEDOR.IDSTATUS = TB_STATUS.IDSTATUS

WHERE
	(TB_FORNECEDOR.CNPJ  like '%'+@CNPJ+'%') or (TB_FORNECEDOR.CNPJ  like '%'+@CNPJ)
or
	(TB_FORNECEDOR.NOMEFANTASIA  like '%'+@RAZAOSOCIALNOMEFANTASIA+'%') or (TB_FORNECEDOR.NOMEFANTASIA  like '%'+@RAZAOSOCIALNOMEFANTASIA)
or
	(TB_FORNECEDOR.RAZAOSOCIAL  like '%'+@RAZAOSOCIALNOMEFANTASIA+'%') or (TB_FORNECEDOR.RAZAOSOCIAL  like '%'+@RAZAOSOCIALNOMEFANTASIA)
 or
	(TB_FORNECEDOR.CODINTERNO  like '%'+@CODINTERNO+'%') or (TB_FORNECEDOR.CODINTERNO  like '%'+@CODINTERNO)
 
