PRINT Db_Name()+', Criação da Procedure USPPranchaFornecedorListar'

GO
--------------------------------------------------------------------------------------
-- OBJETO: USPPranchaFornecedorListar – RESPONSÁVEL: Anderson – DATA: 10/10/2018 – 
--------------------------------------------------------------------------------------
IF EXISTS( SELECT
               NAME
           FROM
               SYSOBJECTS
           WHERE
             XTYPE = 'P'
             AND NAME = 'USPPranchaFornecedorListar' )
    DROP PROCEDURE USPPranchaFornecedorListar

GO

CREATE PROCEDURE USPPranchaFornecedorListar
		   @IDFORNECEDOR int
AS
    SET NOCOUNT ON

SELECT
	TB_PRANCHA.IDPRANCHA, 
	TB_PRANCHA.PRANCHA, 
	TB_PRANCHA.DESCRICAO, 
	TB_PRANCHA.VOLUME, 
	TB_PRANCHA.POLEGADAS, 
	TB_PRANCHA.ESPESSURA, 
	TB_PRANCHA.IDFORNECEDOR, 
	TB_FORNECEDOR.NOMEFANTASIA, 
	TB_FORNECEDOR.RAZAOSOCIAL, 
	TB_FORNECEDOR.CNPJ, 
	TB_FORNECEDOR.CODINTERNO AS CODINTERNOFORNECEDOR, 
	TB_PRANCHA.DATACADASTRO, 
	TB_PRANCHA.IDSTATUS, 
	TB_STATUS.[STATUS], 
	TB_PRANCHA.CODINTERNO AS CODINTERNOPRANCHA,
	TB_PRANCHA.IDMARCA, 
	TB_PRANCHA_MARCA.MARCA, 
	TB_PRANCHA.IDMODELO, 
	TB_PRANCHA_MODELO.MODELO, 
	TB_PRANCHA.TAMANHO, 
	TB_PRANCHA.LARGURA, 
	TB_PRANCHA.BORDA, 
	TB_PRANCHA.LITRAGEM, 
	TB_PRANCHA.IDMODALIDADE, 
	TB_PRANCHA_MODALIDADE.MODALIDADE,
	(SELECT COUNT(IDIMAGEM) FROM TB_PRANCHA_IMAGEM WHERE IDPRANCHA = TB_PRANCHA.IDPRANCHA) AS QUANTIDADEIMAGENS,
	(SELECT TOP 1 IMAGEM FROM TB_PRANCHA_IMAGEM WHERE IDPRANCHA = TB_PRANCHA.IDPRANCHA AND CAPA = 1) AS CAPA
FROM
	TB_PRANCHA 
INNER JOIN
	TB_FORNECEDOR ON TB_PRANCHA.IDFORNECEDOR = TB_FORNECEDOR.IDFORNECEDOR 
INNER JOIN
	TB_STATUS ON TB_PRANCHA.IDSTATUS = TB_STATUS.IDSTATUS 
INNER JOIN
	TB_PRANCHA_MARCA ON TB_PRANCHA.IDMARCA = TB_PRANCHA_MARCA.IDMARCA 
INNER JOIN
	TB_PRANCHA_MODALIDADE ON TB_PRANCHA.IDMODALIDADE = TB_PRANCHA_MODALIDADE.IDMODALIDADE 
INNER JOIN
	TB_PRANCHA_MODELO ON TB_PRANCHA.IDMODELO = TB_PRANCHA_MODELO.IDMODELO
where TB_PRANCHA.IDFORNECEDOR = @IDFORNECEDOR