PRINT Db_Name()+', Criação da Procedure USPRelatorioHOME'

GO
--------------------------------------------------------------------------------------
-- OBJETO: USPRelatorioHOME – RESPONSÁVEL: Anderson – DATA: 10/10/2018 – 
--------------------------------------------------------------------------------------
IF EXISTS( SELECT
               NAME
           FROM
               SYSOBJECTS
           WHERE
             XTYPE = 'P'
             AND NAME = 'USPRelatorioHOME' )
    DROP PROCEDURE USPRelatorioHOME

GO

CREATE PROCEDURE USPRelatorioHOME
	AS
    SET NOCOUNT ON

	execute USPLocacaoRotinaAtualizacao -- Rotina de Atualização de Emprestimos

SELECT
	(SELECT COUNT(IDPRANCHA) from TB_prancha where IDSTATUS = 1	) AS PRANCHAS,
	(SELECT COUNT(IDLOCACAO) FROM TB_LOCACAO WHERE IDSTATUS = 3) AS LOCACOES,
	(SELECT COUNT(IDLOCACAO) FROM TB_LOCACAO WHERE IDSTATUS = 4) AS DEVOLVIDAS,
	(SELECT COUNT(IDLOCACAO) FROM TB_LOCACAO WHERE IDSTATUS = 5) AS LOCACOESATRASADAS,
	(SELECT COUNT(IDLOCACAO) FROM TB_LOCACAO WHERE IDSTATUS = 6) AS LOCACOESDEVOLVIDASATRASADAS,
	(SELECT COUNT(*) FROM TB_PRANCHA WHERE IDSTATUS = 1 AND IDPRANCHA not in (SELECT IDPRANCHA FROM TB_LOCACAO WHERE IDSTATUS = 3 ) ) as PranchaDIsponiveis ,
	(SELECT COUNT(*) FROM TB_CLIENTE WHERE IDSTATUS = 1) as CLIENTES,
	(SELECT COUNT(*) FROM TB_FORNECEDOR WHERE IDSTATUS = 1 AND FABRICANTE = 1) as FORNECEDORES,
	(SELECT COUNT(*) FROM TB_FORNECEDOR WHERE IDSTATUS = 1 AND PONTOENTREGARETIRADA = 1) as PONTOSRETIRADAS,
	(SELECT COUNT(*) FROM TB_PEDIDO WHERE YEAR(DATACADASTRO) = YEAR(GETDATE())) as PEDIDOS



GO 